### ISSUE TITLE
undefined method `ord' for nil:NilClass

### ISSUE THREAD

**Issue by kalda341** [tardate/megar#2]
@session = Megar::Session.new(email: email, password: password)

/home/max/.gem/ruby/1.9.1/gems/megar-0.0.3/lib/megar/crypto/support.rb:304:in `block in decompose_rsa_private_key': undefined method`ord' for nil:NilClass (NoMethodError)

When printing the contents of privk, it seems to be empty at least at some point in the loop, and then the error occurs. Strangely enough, the first connect worked, it's only subsequent ones the won't.

Thanks for a great API.

**Comment by tardate** [comment]
hey, thanks for the report. You're right in that for some reason the RSA private key is not as long as it is expected to be (at the moment, this method doesn't assert a valid key first).

Do you get the error every time you try to connect, or only sometimes?

**Comment by kalda341** [comment]
Every time now, but it seemed to work before.

**Comment by tardate** [comment]
hmm, I'm having trouble reproducing this. I suspect it must either be environmental or something about your account credentials that makes for an unusual situation. If you can help get to the bottom of this I'd really appreciate it. Here are some ideas:
- which OS/version are you using?
- can you run the test specs successfully? `rake spec`
- can you regen test expectations? `rake gen:crypto_expectations email=my@email.com password=mypassword`
- can you setup another account on mega for testing and try with that to see if you can get the same result.

It would be great if you could contact me direct (gallagher.paul@gmail.com) with your findings and so we can discuss out-of-bound, rather than filling the issue notes with diagnostics.

**Comment by kalda341** [comment]
The issue is still there, but doesn't exist on my new account. Must be password length or something.

**Comment by tardate** [comment]
Hey, thanks for the update. You are right - must concern a specific edge case. It would be great if you can give me some more information to test with. If you are no longer using it, the details of your old account would be ideal. Or hints as to length of email and password. Basically anything you are OK to reveal to me. You can contact me direct (gallagher.paul@gmail.com) instead of posting here.

Thanks again for testing it out, much appreciated.

**Comment by dhaneshkhot** [comment]
For below snippet,

post_fix_expr="ab+"
for i in 0..post_fix_expr.length
  puts post_fix_expr[i].ord
end

I'm getting the output the way i want yet it's throwing exception "undefined method `ord" as mentioned below:

97
98
43
D:/Getting started Selenium/RubyStudy/aaaa.rb:4:in `block in <main>': undefined method`ord' for nil:NilClass (NoMethodError)
    from D:/Getting started Selenium/RubyStudy/aaaa.rb:3:in `each'
    from D:/Getting started Selenium/RubyStudy/aaaa.rb:3:in`<main>'

What is the reason for this?

Thanks in advance!,
Dhanesh

**Comment by dhaneshkhot** [comment]
Sorry, my bad.. was checking out of bound element.. 
for i in 0..post_fix_expr.length-1 solved my problem
